# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_convexe_rcpp_hello`)
}

cov <- function(v1,v2){
  .Call(`_M2_algorithme-enveloppe-convexe_dist_Rcpp`, v1, v2)
}
