# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_erase2 <- function(x, colID) {
    .Call(`_ConvexHullLeyth_col_erase2`, x, colID)
}

naif_convex_rcpp <- function(list) {
    .Call(`_ConvexHullLeyth_naif_convex_rcpp`, list)
}

rcpp_hello_world <- function() {
    .Call(`_ConvexHullLeyth_rcpp_hello_world`)
}

